### ISSUE TITLE
Modernise wagtail images

### ISSUE THREAD

**Issue by ahayzen** [ahayzen/nix-config#59]
- [ ] Move to newer debian
- [ ] Move to pypi base or similar?
- [ ] Have CI test the images build and run
- [ ] Automate updating image
- [ ] Can we build static files into the image?

**Comment by ahayzen** [comment]
Static files can be reached via a named volume for an existing directory

eg

```
caddy:
  volumes:
    - static-data:/srv/site/static_data:ro

wagtail:
  volumes:
    - static-data:/mysite/static:ro
```

This would allow for `/srv/site/static_data` of `caddy` to be reading `/mysite/static` of `wagtail`.

https://www.digitalocean.com/community/tutorials/how-to-share-data-between-docker-containers#step-3-creating-a-volume-from-an-existing-directory-with-data
